const constants={
// Table Names
PAYMENT_TABLE:"SGE_PAYMENT",
STUDENT_TABLE:"SGE_STUDENT",
REGISTRATION_TABLE:"SGE_REGISTRATION",
USER_TABLE:"SGE_USER",
FREQUENCY_TABLE:"SGE_FREQUENCY",
LOGININFO_TABLE:"SGE_LOGININFO",
PAYMENTCONFIG_TABLE:"SGE_PAYMENTCONFIG",
SUCURSAL_TABLE:"SGE_SUCURSAL",
SMS_TABLE:"SGE_SMS",
PROFILE_TABLE:"SGE_PROFILE",
FINE_CONFIG_TABLE:"SGE_FINE_CONFIG",
}

module.exports=constants;